# JVM Args
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.227
loader_version_range=[1,)


# Mod Properties
mod_id=extra_gauges
mod_name=Extra Gauges [Forked]
mod_license=MIT
mod_version=1.0.14
mod_group_id=net.liukrast
mod_authors=Liukrast, Francywott
mod_description=Adds new gauges to create connections! (Forked to add support for the Create: Simulated Navigation Table and to correct the expression gauge text length bug)
mod_git=https://github.com/LIUKRAST/CreateExtraGauges
mod_url=https://liukrast.net/
mod_credits=Propants for the initial idea

# Publish
curse_id=1263228
modrinth_id=D6daOdv9
dependencies=create(required){modrinth:LNytGWDc}{curseforge:328085}#(ignore:github)
java_version=21
mod_loader=neoforge

# Other dependencies
create_version_range=[6.0.10,)
create_version = 6.0.10-280
ponder_version = 1.0.82
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+67
jei_version=19.21.1.300
deployer_version_range=[0.1.1,1.0.0)
deployer_version=0.1.2
